force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

school-app/main/default/objects/Teacher__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <defaultValue>21</defaultValue>
    <label>Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TeachersListWithController.cls
public with sharing class TeachersListWithController {

    private String sortOrder = 'Name';

    public TeachersListWithController() {}

    public List<Teacher__c> getTeachers() {
        List<Teacher__c> results = Database.query(
            'SELECT Id, Name, Age__c ' +
            'FROM Teacher__c ' +
            'ORDER BY ' + sortOrder + ' ASC ' +
            'LIMIT 10'
        );
        return results;
    }

    public void sortByName() {
        this.sortOrder = 'Name';
    }

    public void sortByAge() {
        this.sortOrder = 'Age__c';
    }
}