force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

school-app/main/default/objects/Teacher__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <defaultValue>21</defaultValue>
    <label>Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TeachersListControllerTest.cls
@isTest
class TeachersListControllerTest {

    @isTest
    static void testList() {
        List<Teacher__c> teachers = new List<Teacher__c>();

        for (Integer i = 0; i < 10; i++) {
            teachers.add(new Teacher__c(Name = 'Teacher ' + i, Age__c = i));
        }

        insert teachers;

        TeachersListWithController controller = new TeachersListWithController();

        controller.sortByAge();
        controller.sortByName();
        
        Integer expected = 10;
        Integer actual = controller.getTeachers().size();

        System.assert(expected == actual);        
    }
}